JobPortal/Models/Applicant.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace JobPortal.Models
{
    public class Applicant
    {
        [Required]
        [Key]
        public int ApplicantId { get; set; }
        public string Name { get; set; }
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [DataType(DataType.PhoneNumber)]
        public string PhoneNumber { get; set; }
        [DataType(DataType.Url)]
        public string GitHubUrl { get; set; }
        public int JobId { get; set; }
        [ForeignKey("JobId")]
        public virtual Job Job { get; set; }
    }
}

JobPortal/Models/AppliedJob.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace JobPortal.Models
{
    public class AppliedJob
    {
        [Required]
        [Key]
        public int Id { get; set; }
        public int ApplicantId { get; set; }
        [ForeignKey("ApplicantId")]
        public virtual Applicant Applicant { get; set; }
        public int JobId { get; set; }
        [ForeignKey("JobId")]
        public virtual Job Job { get; set; }
    }
}

JobPortal/Models/Job.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace JobPortal.Models
{
    public class Job
    {
        [Required]
        [Key]
        public int JobId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int NoOfPositions { get; set; }
        public int ApplicantId { get; set; }
        public ICollection<Applicant> applicant{ get; set; }
    }
}

JobPortal/Models/JobPortalContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace JobPortal.Models
{
    public class JobPortalContext : DbContext
    {
        public DbSet<Applicant> Applicant { get; set; }
        public DbSet<Job> Job { get; set; }
        //public DbSet<AppliedJob> AppliedJob { get; set; }
    }
}

JobPortal/Controllers/ApplicantController.cs
using JobPortal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace JobPortal.Controllers
{
    public class ApplicantController : Controller
    {
            private JobPortalContext db = new JobPortalContext();
           
            public ActionResult Apply()
            {
            return View();
            }
            [HttpPost]
            public ActionResult Apply([Bind(Include="Name , Email, PhoneNumber,GitHubUrl")] Applicant applicant)
            {
                if (ModelState.IsValid)
                {
                    db.Applicant.Add(applicant);
                    
                    db.SaveChanges();
                    return RedirectToAction("Detail","Job");
                }

                return View(applicant);
            }
            public ActionResult List(Job job)
            {
                return View(db.Job.ToList());
            }
        }
    }

JobPortal/Controllers/JobController.cs
using JobPortal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace JobPortal.Controllers
{
    public class JobController : Controller
    {
        private JobPortalContext db = new JobPortalContext();
        // GET: Job
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add(Job job)
        {
            if (ModelState.IsValid)
            {
                db.Job.Add(job);
                db.SaveChanges();
                return RedirectToAction("List");
            }

            return View(job);
        }
        public ActionResult List(Job job)
        {
            return View(db.Job.ToList());
        }
        public ActionResult Detail(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Job.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

    }
}

JobPortal/Views/Applicant/Add.cshtml
@model JobPortal.Models.Applicant

@{
    ViewBag.Title = "Add";
}

<h4> ...Applicant...</h4>
<h2>Add</h2>

@using (Html.BeginForm())
{
    <hr />
    
    <div>
        @Html.LabelFor(model => model.Name)
        @Html.EditorFor(model => model.Name)
    </div>
    <div>
        @Html.LabelFor(model => model.Email)
        @Html.EditorFor(model => model.Email)
        @Html.ValidationMessageFor(model => model.Email)
       
    </div>
    <div>
        @Html.LabelFor(model => model.PhoneNumber)
        @Html.EditorFor(model => model.PhoneNumber)
        @Html.ValidationMessageFor(model => model.PhoneNumber)
    </div>
    <div>
        @Html.LabelFor(model => model.GitHubUrl)
        @Html.EditorFor(model => model.GitHubUrl)
        @Html.ValidationMessageFor(model => model.GitHubUrl)
    </div>
    <div>
        <input type="submit" value="Add" />
    </div>
}

@Html.ActionLink("Job List", "List","Job")

JobPortal/Views/Job/Add.cshtml
@model JobPortal.Models.Job

@{
    ViewBag.Title = "JobAdd";
}

<h4> ...Job...</h4>

<h2>Add</h2>

@using (Html.BeginForm())
{
    <hr />
    <div>
        @Html.LabelFor(model => model.Name)
        @Html.EditorFor(model => model.Name)
    </div>
    <div>
        @Html.LabelFor(model => model.Description)
        @Html.EditorFor(model => model.Description)
    </div>
    <div>
        @Html.LabelFor(model => model.NoOfPositions)
        @Html.EditorFor(model => model.NoOfPositions)
    </div>
    <div>
        <input type="submit" value="Add" />
    </div>
}

@Html.ActionLink("Job List","List")

JobPortal/Views/Job/Detail.cshtml
@model JobPortal.Models.Job

@{
    ViewBag.Title = "Detail";
}
<h4>Job</h4>

<h2>Detail</h2>
<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NoOfPositions)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoOfPositions)
        </dd>
        


    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "List")
</p>

JobPortal/Views/Job/List.cshtml
@model IEnumerable<JobPortal.Models.Job>

@{
    ViewBag.Title = "List";
}

<h4> ... Jobs ... </h4>
<h2>List</h2>
<div>
<table border="1" cellspacing="3" cellpadding="2">
   
    <tr>
        <th>
             @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NoOfPositions)
        </th>
        <th>
            @Html.Label("Action");
        </th>
    </tr>
    @foreach (var item in Model)
    { 
        <tr>
            <td>
                @Html.DisplayFor(modeItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modeItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modeItem => item.NoOfPositions)
            </td>
            <td>
                @Html.ActionLink("Apply", "Add", "Applicant")   
                @Html.ActionLink("View", "Detail", new { id = item.JobId })
                
            </td>
        </tr>
    }
</table>
</div>

JobPortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>